name: Build rohmu

# Default to read-only access to all APIs.
permissions: read-all

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:

jobs:

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # only use one version for the lint step
        python-version: [3.9]

    steps:

      - id: checkout-code
        uses: actions/checkout@v2
        with:
          # Do not persist the token during execution of this job.
          persist-credentials: false

      - id: prepare-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - id: dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements.dev.txt

      - id: pylint
        run: make lint

      - id: mypy
        run: make mypy

      - id: validate-style
        run: |
          make fmt
          if [ $(git diff --name-only --diff-filter=ACMR | wc -l ) != 0 ]; then
            echo "Reformatting failed! Please run make fmt on your commits and resubmit!" 1>&2;
            git diff;
            exit 1;
          fi

  test:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.8, 3.7, 3.6]

    steps:
      - id: checkout-code
        uses: actions/checkout@v2

      - id: prepare-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - id: unittest
        run: make coverage
